nba_question_bank = {
        "Who holds the record for the most NBA championships?": "Bill Russell",
        "Who is the all-time leading scorer in the NBA?": "LeBron James",
        "Who is the all-time leader in rebounds in the NBA?": "Wilt Chamberlain",
        "Who is the all-time leader in assists in the NBA?": "John Stockton",
        "Who is the all-time leader in steals in the NBA?": "John Stockton",
        "Who is the all-time leader in blocks in the NBA?": "Hakeem Olajuwon",
        "Who is the all-time leader in 3-pointers made in the NBA?": "Stephen Curry",
        "Who is the all-time leader in free throws made in the NBA?": "Jerry West",
        "Who is the all-time leader in points per game in the NBA?": "Michael Jordan",
        "Who is the all-time leader in free throws made per game in the NBA? ": "Shaquille O'Neal",
        "Who is the all-time leader in triple-doubles in the NBA?": "Oscar Robertson",
        "Who is the all-time leader in 3-pointers made in a single NBA game?": "Klay Thompson",
        "How many teams are there in the NBA?": "30 teams",
        "Which team from the 1980s were known as the Bad Boys?": "Detroit Pistons",
        "Which team famously went 72-10 in the 1995-96 NBA regular season?": "Chicago Bulls",
        "How many NBA championships have the Boston Celtics won?": "17 Championships",
        "How many NBA championships have the Los Angeles Lakers won?": "17 Championships",
        "Who has won the most NBA championships as a coach?": "Phil Jackson",
        "Who owns the New York Knicks?": "James Dolan",
        "What is the minimum age requirement for an NBA player?": "19 years old",
        "How long is an NBA game?": "48 minutes",
        "How many players can be on a team's active roster?": "15 players",
        "Name all 4 teams Ray Allen played for": "Bucks, Supersonics, Celtics and Heat",
        "Which team won back to back championships in '94 and '95?": "Houston Rockets",
        "Which team had the nickname Lob City?": "LA Clippers",
        "What 3 teams have played in the most playoff games?": "Celtics, Lakers, 76ers",
        "Name all 4 teams Paul Pierce played for": "Nets, Celtics, Wizards and Clippers",
        "Who is the last Spurs player to win Finals MVP?": "Kawhi Leonard",
        "Which player has the best winning percentage of all time?": "Kawhi Leonard",
        "Which two players are tied for most all star selections?": "Kareem Abdul Jabar and Lebron James",
        "Name the all star that was selected 1 pick after Kevin Durant in the '07 draft": "Al Horford",
        "Which team drafted Kawhi Leonard?": "Indiana Pacers",
        "What number did Michael Jordan wear during the Olympics?": "9",
        "Name any player that has won 3 consecutive NBA MVPs": "Larry Bird, Wilt Chamberlain, Bill Russell",
        "Which team drafted Andre Iguadola?": "Philadelphia 76ers",
        "Name the only rookie to win Finals MVP": "Magic Johnson",
        "Name the 2 Knicks players selected to the all star game in 2013": "Carmelo Anthony, Tyson Chandler",
        "Name the only 2 Spurs players to win league MVP": "Tim Duncan, David Robinson",
        "Who did the Knicks pick #4 overall in the 2015 NBA draft?": "Kristaps Porzingis",
        "Which NBA allstar played with Russell Westbrook at UCLA?": "Kevin Love",
        "Which team won 3 championships from 2003 to 2007?": "San Antonio Spurs",
        "Name the player with the most steals in Washington Wizards franchise history": "John Wall",
        "Name the only 2 players who have won 7 consecutive scoring titles": "Wilt Chamberlain, Michael Jordan",
        "Name the 2 players picked before Luka in the 2018 draft": "Deandre Ayton, Marvin Bagley",
        "Name the first point guard to win defensive player of the year": "Gary Payton",
        "Which player was draft #2 overall after Zion Williamson in 2019?": "Ja Morant",
        "Which player won 3 defensive player of the year awards from 2018-2021?": "Rudy Gobert",
        "Which team originally drafted Rajon Rondo?": "Phoenix Suns",
        "Name all the teams that beat Lebron James in the NBA finals": "Warriors, Mavericks, Spurs",
        "Name all 3 teams that Dywane Wade played for": "Heat, Cavaliers, Bulls",
        "From 2015-2017, the LA Lakers had the 2nd overall pick each year. Name all 3 players that they drafted": "Brandon Ingram, Lonzo Ball, D'angelo Russell",
        "Name the only 2 Milkwaukee Bucks players to win NBA MVP": "Giannis Antetokounmpo and Kareem Abdul Jabar",
        "Which player won all star MVP, NBA MVP, and Finals MVP in the year 2000?": "Shaquille O'neal",
        "Who is the only Harlem Globetrotter to win NBA MVP?": "Wilt Chamberlain",
        "Who is the oldest player to score 50+ points in a single NBA game?": "Jamal Crawford",
        "Which team drafted Vince Carter?": "Golden State Warriors",
        "Name the 2 teams that retired #23 for Michael Jordan": "Chicago Bulls, Miami Heat",
        "Name the only person to win NBA MVP, Finals MVP, Coach of the Year and Executive of the Year?": "Larry Bird",
        "Who was the first unanimous NBA MVP?": "Stephen Curry",
        "Who is the youngest NBA player to score 10,000 points?": "Lebron James",
        "Which team drafted Julius Irving?": "Milwaukee Bucks",
        "Which team drafted Julius Randle?": "Los Angeles Lakers",
        "Which NBA player was nicknamed The Glide?": "Clyde Drexler",
        "Who is the only NBA player to retire with more blocked shots than points scored?": "Manute Bol",
        "Which Toronto Raptors coach was fired the same year he won Coach of the Year?": "Dwyane Casey",
        "Who is the youngest NBA player to score 20+ points in 10 consecutive games?": "Zion Williamson",
        "Which controversial playe was not selected for the 1992 Dream Team even though he met the criteria?": "Isaiah Thomas",
        "Name the top 3 players to have the most 3 pointers made in NBA history": "Stephen Curry, Ray Allen, James Harden",
        "Who is the all time leader in points for the Miami Heat?": "Dwayne Wade",
        "Name the 2 teams Kobe Bryant lost to in the Finals": "Celtics and Pistons",
        "Which team originally drafted Dennis Rodman?": "Detroit Pistons",
        "Who has the highest 3 point percentage of all time?": "Steve Kerr",
        "Name the all time points leader for the Orlando Magic": "Dwight Howard",
        "Name the top 3 assist leaders of all time": "Jason Kidd, Chris Paul, John Stockton",
        "What college did Carmelo Anthony play for?": "Syracuse",
        "Who has the best single season field goal percentage of all time?": "Mitchell Robinson",
        "Name the youngest player to win NBA MVP": "Derrick Rose",
        "Name the 4 NBA teams who's name don't end in an S": "Thunder, Magic, Heat, Jazz",
        "Which player has the best career winning percentage?": "Kawhi Leonard",
        "Name the player that has won the most Finals MVPs": "Michael Jordan",
        "Which franchise had the worst record in a single season in history?": "Charlotte Bobcats",
        "Who is the all time leading scorer for the Pacers?": "Reggie Miller",
        "Name the only player to win MVP, Defensive Player of the Year and Finals MVP in the same season": "Hakeem Olajuwon",
        "Who's nickname was The Answer?": "Allen Iverson",
        "Who is the tallest player in NBA history?": "Manute Bol",
        "Who is the oldest player to record a triple double?": "Karl Malone",
        "What teams did the Bulls beat in their first 3-Peat?": "Suns, Lakers, Trail Blazers",
        "Which team originally drafted Chris Paul?": "New Orleans Hornets",
        "Who has the worst free throw percentage of all time with 1000 minimum attempts?": "Ben Wallace",
        "Name a player that has won Sixth Man of the Year and league MVP in their career": "James Harden and Bill Walton",
        "Who made the game winning shot in ame 6 of the 1997 NBA finals for the Chicago Bulls?": "Steve Kerr",
        "What team was the first to come back 3-1 in the NBA finals and win?": "Cleveland Cavaliers",
        "What NBA team did Phil Jackson play for?": "New York Knicks",
        "Name all 6 teams that Shaquille O'Neal played for": "Heat, Celtics, Lakers, Magic, Cavaliers, Suns",
        "Name the team the Chicago Bulls beat back to back in the '97 and '98 NBA Finals": "Utah Jazz",
        "Which player has the most missed shots in NBA history?": "Kobe Bryant",
        "Which team has the record for highest points per game in a single season?": "Denver Nuggets",
        "Which NBA team has the most losses in Finals history?": "Los Angeles Lakers",
        "Which player is used in the NBA logo?": "Jerry West",
        "How many teams are there in each NBA division?": "5 teams",
        "Which player has the most dunks all time in the NBA?": "Dwight Howard",
        "Who is the all time leading scorer for the Atlanta Hawks?": "Dominique Wilkins",
        "Who is the youngest player in NBA history to record a triple double?": "Lamelo Ball"
}